### ISSUE TITLE
Icons replicate when you move the map

### ISSUE THREAD

**Issue by jill-cardamon** [mapbox/mapbox-navigation-ios-examples#98] opened 2021-04-15 15:30 UTC
### Steps to reproduce

 1. Select either Advanced Implementation or Custom Waypoint Styling example
 2. Long press to generate route and start navigation
 3. Drag map around

### Expected behavior
`Mapbox` and information icons don't replicate when map is dragged.

![Simulator Screen Shot - iPhone 8 Plus - 2021-04-15 at 11 25 42](https://user-images.githubusercontent.com/43434254/114895350-7028fe00-9ddd-11eb-9736-2e971d328e16.png)

### Actual behavior
`Mapbox` and information icons replicate when map is dragged.

![Simulator Screen Shot - iPhone 8 Plus - 2021-04-15 at 11 25 45](https://user-images.githubusercontent.com/43434254/114895479-89ca4580-9ddd-11eb-868e-388c932edb24.png)

**Comment by 1ec5** [comment] 2021-04-16 15:21
The Mapbox logo also duplicates, though it’s harder to tell because the duplicates are obscured by the Resume button. I’m guessing the map SDK code that installs the ornaments is being rerun too many times.

**Comment by MaximAlien** [comment] 2021-05-04 15:03
Looks like issue is no longer reproducible in Navigation SDK `v2.0.0-beta.7`. Closing this ticket.

**Comment by MaximAlien** [comment] 2021-05-04 15:04
@jill-cardamon, please re-open if you can still reproduce this issue.

**Closed by MaximAlien** 2021-05-04 15:03 UTC
Labels: bug

**Comment by jill-cardamon** [comment] 2021-05-04 20:34
I can't reproduce it.
